apiVersion: apps/v1
kind: Deployment
metadata:
  name: random
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random
  template:
    metadata:
      labels:
        app: random
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: random
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3398e181-d9fb-4c1a-bc90-e46efa66dfbd"
        - name: Vless_Path
          value: "/vpath"
        - name: Vmess_UUID
          value: "7f7c9ba0-35df-4818-a7d4-f8839824e328"
        - name: Vmess_Path
          value: "/vmpath"
        - name: Share_Path
          value: "/v2link"
